# Generated by Django 4.1.4 on 2024-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(db_index=True, max_length=30)),
                ('model', models.CharField(db_index=True, max_length=30)),
                ('manufacturer', models.CharField(db_index=True, max_length=30)),
                ('price', models.IntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'tool',
                'verbose_name_plural': 'tools',
                'ordering': ('model',),
            },
        ),
    ]
